"""phone number and dail code to string column for user schema

Revision ID: 35f1f3713073
Revises: 7276b4753f03
Create Date: 2026-07-16 16:06:40.082810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f1f3713073'
down_revision: Union[str, Sequence[str], None] = '7276b4753f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dial_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('users', 'dial_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
