"""Create Pdf Table

Revision ID: 813765128726
Revises: 
Create Date: 2026-07-17 11:34:40.147652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813765128726'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_filename'), 'pdf', ['filename'], unique=True)
    op.create_index(op.f('ix_pdf_filepath'), 'pdf', ['filepath'], unique=True)
    op.create_index(op.f('ix_pdf_uploaded_at'), 'pdf', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_uploaded_at'), table_name='pdf')
    op.drop_index(op.f('ix_pdf_filepath'), table_name='pdf')
    op.drop_index(op.f('ix_pdf_filename'), table_name='pdf')
    op.drop_table('pdf')
    # ### end Alembic commands ###
